[package]
name = "plutocradroid"
version = "0.1.0"
authors = ["Shelvacu <shelvacu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8"
diesel = { version = "1.0.0", features = ["postgres", "r2d2", "chrono", "numeric"] }
dotenv = "0.9.0"
lazy_static = "*"
regex = "1"
chrono = "*"
bigdecimal = "*"
maplit = "1.0.2"
ordinal = "*"
iron = "0.6.*"
router = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.1"
rocket = "0.4.5"
rocket_oauth2 = "0.4.1"
log = "0.4.11"
reqwest = "0.10.8"
rand = "0.7.3"
base64 = "0.13.0"
maud = { version = "*", features = ["rocket"] }
atoi = "0.3.2"
env_logger = "0.8.1"

[build-dependencies]
vergen = "3"

[features]
debug = []
